services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  AdminUser:
    class: App\Admin\AdminUser
    arguments: [ ~, App\Entity\User, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: User, group: Users }

  IdeaBoxAdmin:
    class: App\Admin\IdeaBoxAdmin
    arguments: [ ~, App\Entity\IdeaBox, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: IdeaBox, group: IdeaBox }
