sonata_formatter:
  default_formatter: text
  formatters:
    text:
      service: sonata.formatter.text.text
      extensions:
        - sonata.formatter.twig.control_flow
        - sonata.formatter.twig.gist
  ckeditor:
    templates:
      browser: '@SonataFormatter/Ckeditor/browser.html.twig'
      upload: '@SonataFormatter/Ckeditor/upload.html.twig'