sonata_media:
    class:
        media: App\Entity\SonataMedia\SonataMediaMedia
        gallery: App\Entity\SonataMedia\SonataMediaGallery
        gallery_has_media: App\Entity\SonataMedia\SonataMediaGalleryHasMedia
        category: App\Entity\SonataClassificationCategory
    db_driver: doctrine_orm
