name: Tests

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --with-dependencies

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Run unit test
        run: |
          php vendor/bin/codecept run unit

      - name: Run functional test
        run: |
          php vendor/bin/codecept run functional
